# This file was generated by GoReleaser. DO NOT EDIT.
cask "geet" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "d7709eafd29d273c40399c39ab2ea2963408992a816e1db4b358807f33ecfa57"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e76d7ca235b056c2981c202cc5aa9cc7ff73be7da6f9b6fae6010d330dd3d03a"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8cf00e66335aa5b57a6a733dca487e412f87f9fa587e9580588d79f77e2c3c11"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f4e4442cfcb74ef9c9a854bf16ae13c3f525130236b195acecfadcad4c424fc2"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "geet"
  desc "Download Spotify tracks, albums and playlists as tagged audio (yt-dlp + ffmpeg)"
  homepage "https://github.com/sumdahl/geet"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "geet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/geet"]
    end
  end

  # No zap stanza required
end
