# This file was generated by GoReleaser. DO NOT EDIT.
cask "geet" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "ff14ea4ec3b0306ff960f653baa02d051261195c850d1ce27af34ba74075e812"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "257f4d4999c86efeaacf8d621ab1877337eed87b3fa29ecc2f6df504ba4cf0ea"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "78d2eb689c58cfa3f121a196900cfae36e31c3d588feeb68be4738db3d1fc672"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ee1b3120f503aca4a1c83a45cbc0bbf81720b6b4250e25aab5cca723d17289d"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "geet"
  desc "Download Spotify tracks, albums and playlists as tagged audio (yt-dlp + ffmpeg)"
  homepage "https://github.com/sumdahl/geet"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "geet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/geet"]
    end
  end

  # No zap stanza required
end
