# This file was generated by GoReleaser. DO NOT EDIT.
cask "geet" do
  version "0.4.6"

  on_macos do
    on_arm do
      sha256 "040f775752c7a558abef414b85326f0b01588034b715e27b280f6adf35feea7e"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7a3db5633b001f29ad3fd5bb44b7cef24f92e9f926b54053815a438fbb8c9fc"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1b57248cbdb9490fcc48cd176db4fd682b20aa933743798f2498c77ac12da49d"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "327e8f79437fbc610499e5eb593d57c3d59abbf06baed284f5df0eec64f122e1"
      url "https://github.com/sumdahl/geet/releases/download/v#{version}/geet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "geet"
  desc "Download Spotify tracks, albums and playlists as tagged audio (yt-dlp + ffmpeg)"
  homepage "https://github.com/sumdahl/geet"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "geet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/geet"]
    end
  end

  # No zap stanza required
end
